In [503]:
import pandas as pd
from collections import Counter
import numpy as np
from sklearn_pandas import CategoricalImputer
from numpy import array
from sklearn.preprocessing import Imputer,LabelEncoder,OneHotEncoder
from sklearn.cross_validation import train_test_split

In [504]:
##imputer for integer
def imputer(X,stra):
    X1=X.reshape(-1,1)
    imputer=Imputer(missing_values='NaN',strategy=stra)
    imputer=imputer.fit_transform(X1)
    X1=imputer
    return X1[:,0]
##imputer for categories
def cat_imputer(X):
    imputer=CategoricalImputer()
    imputer=imputer.fit_transform(X)
    X=imputer
    return X

In [505]:
#load training data
train_data=pd.read_csv('train.csv')

In [506]:
##index location 
x=train_data.iloc[:,[2,4,5,6,7,9,11]]
y=train_data.iloc[:,1]

In [507]:
x=x.values
y=y.values
x[0]

array([3, 'male', 22.0, 1, 0, 7.25, 'S'], dtype=object)

In [508]:
x[:,6]=cat_imputer(x[:,6]) ##embark imputing
x[:,2]=imputer(x[:,2],'mean')##age imputing

In [509]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0)##splitting training and test data
print('training :',x_train.shape,'test :',x_test.shape)

training : (891, 7) test : (0, 7)


In [510]:
def encode(X):
    #x_train[:,6]=x_train[:,6].astype(str)
    values=X
    #print(values)
    #print(np.shape(values))
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)
    #print(integer_encoded)
    # binary encode
    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    return onehot_encoded
    #print(onehot_encoded)

In [511]:
##Sex encode
sex_encoded=encode(x_train[:,1])

In [512]:
x_train=np.column_stack((x_train[:,(0,2,3,4,5,6)],sex_encoded)) 
x_train[0]

array([2, 45.0, 1, 1, 26.25, 'S', 1.0, 0.0], dtype=object)

In [513]:
##embarke encoding
embarke_encode=encode(x_train[:,5])

In [514]:
x_train=np.column_stack((x_train[:,(0,1,2,3,4,6,7)],embarke_encode))

In [515]:
x_train[0]

array([2, 45.0, 1, 1, 26.25, 1.0, 0.0, 0.0, 0.0, 1.0], dtype=object)

In [516]:
from sklearn.naive_bayes import GaussianNB

In [517]:
classifier=GaussianNB()

In [518]:
classifier.fit(x_train,y_train)

GaussianNB(priors=None)

In [519]:
y_pred=classifier.predict(x_train)

In [520]:
#y_pred

In [521]:
from sklearn.metrics import confusion_matrix

In [522]:
acc=confusion_matrix(y_train,y_pred)

In [523]:
acc

array([[454,  95],
       [ 91, 251]], dtype=int64)

In [524]:
accurracy=np.divide(acc[0,0]+acc[1,1],891)

In [525]:
accurracy

0.7912457912457912

In [570]:
#load test data
test_data=pd.read_csv('test.csv')

In [571]:
x_test=test_data.iloc[:,[1,3,4,5,6,8,10]].values

In [572]:
x_test[0]

array([3, 'male', 34.5, 0, 0, 7.8292, 'Q'], dtype=object)

In [573]:
x_test[:,6]=cat_imputer(x_test[:,6])
x_test[:,2]=imputer(x_test[:,2],'mean')
x_test[:,5]=imputer(x_test[:,5],'mean')
x_test[0]

array([3, 'male', 34.5, 0, 0, 7.8292, 'Q'], dtype=object)

In [574]:
##Sex encode
sex_encoded=encode(x_test[:,1])

In [575]:
x_test=np.column_stack((x_test[:,(0,2,3,4,5,6)],sex_encoded)) 
x_test[0]

array([3, 34.5, 0, 0, 7.8292, 'Q', 0.0, 1.0], dtype=object)

In [576]:
embarke_encode=encode(x_test[:,5])

In [577]:
x_test=np.column_stack((x_test[:,(0,1,2,3,4,6,7)],embarke_encode))

In [578]:
x_test[0]

array([3, 34.5, 0, 0, 7.8292, 0.0, 1.0, 0.0, 1.0, 0.0], dtype=object)

In [579]:
y_pred=classifier.predict(x_test)

In [580]:
import csv

In [581]:
with open('pred.csv','w') as csvfile:    
    writer = csv.writer(csvfile)
# Gives the header name row into csv
    schema = ['PassengerId','Survived']
    writer.writerow([g for g in schema]) 
#Data add in csv file       
    for i in range(418):
        generators = [str(i+892), str(y_pred[i])]
        writer.writerow([g for g in generators])

In [582]:
y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,